"""add innovation curve band/score columns

Revision ID: 16ff4bd31cc6
Revises: 6e7fa25f2bc8
Create Date: 2026-07-15 14:03:20.481677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ff4bd31cc6'
down_revision = '6e7fa25f2bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('innovation_band', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('innovation_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('innovation_score')
        batch_op.drop_column('innovation_band')

    # ### end Alembic commands ###
