"""add submission.audience

Revision ID: 6e7fa25f2bc8
Revises: cb6a0d053104
Create Date: 2026-07-15 09:34:35.752211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7fa25f2bc8'
down_revision = 'cb6a0d053104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('audience')

    # ### end Alembic commands ###
