"""create submission table

Revision ID: cb6a0d053104
Revises: 
Create Date: 2026-07-14 22:37:19.544477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6a0d053104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('persona_id', sa.String(length=32), nullable=True),
    sa.Column('score_vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_token'))
        batch_op.drop_index(batch_op.f('ix_submission_created_at'))

    op.drop_table('submission')
    # ### end Alembic commands ###
